import { MissionDefinition } from './MissionDefinition';
import { ENEMY_GRUNT, ENEMY_ARCHER, ENEMY_BRUTE, ENEMY_BOSS } from '../ai/EnemyStats';
import { SUPPLY_DROP_INTERVAL_MS, CAMP_AGGRO_DEFAULT } from '../config';

export const MISSIONS: MissionDefinition[] = [
  // ── Mission 1: Easy ──────────────────────────────────────────
  {
    id: 'purge_outskirts',
    name: 'Purge the Outskirts',
    description: 'Clear xenos nests from the landing zone perimeter. Destroy the ork camp and purge the spawning grounds.',
    difficulty: 1,
    playerStartX: 40,
    playerStartY: 40,
    startingGold: 30,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    terrain: {
      waterCoverage: 0.06,
      stoneCoverage: 0.03,
      forestCoverage: 0.05,
      goldMineCount: 6,
      riverCount: 1,
    },
    objectives: [
      {
        id: 'obj_destroy_camp1',
        type: 'destroy',
        name: 'Destroy Ork Outpost',
        description: 'Raze the ork outpost to the northwest.',
        tileX: 16,
        tileY: 16,
        targetCampId: 'camp_ork_nw',
        goldReward: 20,
        cardDraws: 2,
      },
      {
        id: 'obj_purge_nest',
        type: 'purge',
        name: 'Purge Xenos Nest',
        description: 'Eliminate all hostiles near the eastern spawning ground.',
        tileX: 64,
        tileY: 28,
        purgeRadius: 7,
        goldReward: 20,
        cardDraws: 2,
      },
    ],
    enemyCamps: [
      {
        id: 'camp_ork_nw',
        tileX: 16,
        tileY: 16,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 100, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 30000,
          spawnGroup: [{ type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 }],
          maxActiveUnits: 6,
          patrolRadius: 8,
        },
      },
      {
        id: 'camp_east_nest',
        tileX: 64,
        tileY: 28,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
        ],
      },
      {
        id: 'camp_south_patrol',
        tileX: 30,
        tileY: 64,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 30, y: 64 }, { x: 40, y: 64 }, { x: 40, y: 56 }, { x: 30, y: 56 },
        ],
      },
    ],
  },

  // ── Mission 2: Medium ─────────────────────────────────────────
  {
    id: 'secure_relay',
    name: 'Secure the Relay',
    description: 'Destroy ork outposts and recover the vox relay to restore Imperial communications.',
    difficulty: 2,
    playerStartX: 40,
    playerStartY: 68,
    startingGold: 25,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    terrain: {
      waterCoverage: 0.08,
      stoneCoverage: 0.04,
      forestCoverage: 0.07,
      goldMineCount: 8,
      riverCount: 2,
    },
    objectives: [
      {
        id: 'obj_destroy_east',
        type: 'destroy',
        name: 'Destroy Eastern Outpost',
        description: 'Demolish the ork fortification to the east.',
        tileX: 66,
        tileY: 46,
        targetCampId: 'camp_ork_east',
        goldReward: 20,
        cardDraws: 2,
      },
      {
        id: 'obj_destroy_north',
        type: 'destroy',
        name: 'Destroy Northern Outpost',
        description: 'Demolish the ork fortification to the north.',
        tileX: 40,
        tileY: 12,
        targetCampId: 'camp_ork_north',
        goldReward: 20,
        cardDraws: 2,
      },
      {
        id: 'obj_recover_relay',
        type: 'recover',
        name: 'Recover Vox Relay',
        description: 'Send a unit to the relay site to recover it.',
        tileX: 14,
        tileY: 24,
        goldReward: 25,
        cardDraws: 2,
      },
    ],
    enemyCamps: [
      {
        id: 'camp_ork_east',
        tileX: 66,
        tileY: 46,
        aggroRadius: CAMP_AGGRO_DEFAULT + 1,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 120, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
            { type: 'enemy_archer', texture: 'unit-enemy-ranged', stats: ENEMY_ARCHER, count: 1 },
          ],
          maxActiveUnits: 8,
          patrolRadius: 10,
        },
      },
      {
        id: 'camp_ork_north',
        tileX: 40,
        tileY: 12,
        aggroRadius: CAMP_AGGRO_DEFAULT + 1,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 120, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
            { type: 'enemy_archer', texture: 'unit-enemy-ranged', stats: ENEMY_ARCHER, count: 1 },
          ],
          maxActiveUnits: 8,
          patrolRadius: 10,
        },
      },
      {
        id: 'camp_relay_guard',
        tileX: 14,
        tileY: 24,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
      },
      {
        id: 'camp_south_flank',
        tileX: 60,
        tileY: 66,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 60, y: 66 }, { x: 68, y: 66 }, { x: 68, y: 58 }, { x: 60, y: 58 },
        ],
      },
      {
        id: 'camp_west_ambush',
        tileX: 12,
        tileY: 50,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
      },
    ],
  },

  // ── Mission 3: Hard ───────────────────────────────────────────
  {
    id: 'exterminatus',
    name: 'Exterminatus Protocol',
    description: 'Slay the Warboss, purge the nesting grounds, and recover the holy relic. The Emperor demands total victory.',
    difficulty: 3,
    playerStartX: 40,
    playerStartY: 70,
    startingGold: 20,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    terrain: {
      waterCoverage: 0.10,
      stoneCoverage: 0.05,
      forestCoverage: 0.08,
      goldMineCount: 8,
      riverCount: 2,
    },
    objectives: [
      {
        id: 'obj_destroy_warboss',
        type: 'destroy',
        name: 'Destroy the Warboss Camp',
        description: 'Eliminate the Warboss and his stronghold.',
        tileX: 40,
        tileY: 8,
        targetCampId: 'camp_warboss',
        goldReward: 30,
        cardDraws: 3,
      },
      {
        id: 'obj_purge_west',
        type: 'purge',
        name: 'Purge Western Nest',
        description: 'Clear all hostiles from the western spawning ground.',
        tileX: 10,
        tileY: 36,
        purgeRadius: 8,
        goldReward: 25,
        cardDraws: 2,
      },
      {
        id: 'obj_purge_east',
        type: 'purge',
        name: 'Purge Eastern Nest',
        description: 'Clear all hostiles from the eastern spawning ground.',
        tileX: 70,
        tileY: 36,
        purgeRadius: 8,
        goldReward: 25,
        cardDraws: 2,
      },
    ],
    enemyCamps: [
      // Warboss camp — heavily fortified
      {
        id: 'camp_warboss',
        tileX: 40,
        tileY: 8,
        aggroRadius: CAMP_AGGRO_DEFAULT + 2,
        units: [
          { type: 'enemy_boss', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BOSS },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 250, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 20000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 3 },
            { type: 'enemy_archer', texture: 'unit-enemy-ranged', stats: ENEMY_ARCHER, count: 1 },
          ],
          maxActiveUnits: 10,
          patrolRadius: 12,
        },
      },
      // West nest
      {
        id: 'camp_west_nest',
        tileX: 10,
        tileY: 36,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 6, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
      },
      // East nest
      {
        id: 'camp_east_nest',
        tileX: 70,
        tileY: 36,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 6, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
      },
      // Forward guard camps
      {
        id: 'camp_mid_left',
        tileX: 20,
        tileY: 20,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 100, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [{ type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 }],
          maxActiveUnits: 6,
          patrolRadius: 8,
        },
      },
      {
        id: 'camp_mid_right',
        tileX: 60,
        tileY: 20,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 100, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [{ type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 }],
          maxActiveUnits: 6,
          patrolRadius: 8,
        },
      },
      // Patrol camps near player start
      {
        id: 'camp_south_patrol_l',
        tileX: 20,
        tileY: 58,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 20, y: 58 }, { x: 28, y: 58 }, { x: 28, y: 50 }, { x: 20, y: 50 },
        ],
      },
      {
        id: 'camp_south_patrol_r',
        tileX: 60,
        tileY: 58,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 60, y: 58 }, { x: 68, y: 58 }, { x: 68, y: 50 }, { x: 60, y: 50 },
        ],
      },
    ],
  },

  // ── Mission 4: Space Hulk ──────────────────────────────────────
  {
    id: 'space_hulk_alpha',
    name: 'Purge the Derelict',
    description: 'Board the space hulk "Malediction of Sorrow" and purge the xenos infestation from its corridors.',
    difficulty: 2,
    playerStartX: 10,
    playerStartY: 40,
    startingGold: 25,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    terrain: {
      mapType: 'space_hulk',
      corridorWidth: 3,
      goldMineCount: 5,
    },
    objectives: [
      {
        id: 'obj_destroy_bridge',
        type: 'destroy',
        name: 'Destroy Bridge Infestation',
        description: 'Clear the xenos nest from the bridge of the derelict.',
        tileX: 60,
        tileY: 20,
        targetCampId: 'camp_bridge',
        goldReward: 20,
        cardDraws: 2,
      },
      {
        id: 'obj_purge_enginarium',
        type: 'purge',
        name: 'Purge the Enginarium',
        description: 'Eliminate all hostiles in the engine chambers.',
        tileX: 40,
        tileY: 65,
        purgeRadius: 6,
        goldReward: 20,
        cardDraws: 2,
      },
      {
        id: 'obj_recover_relic',
        type: 'recover',
        name: 'Recover Sacred Relic',
        description: 'Retrieve the holy relic from the chapel vault.',
        tileX: 70,
        tileY: 50,
        goldReward: 25,
        cardDraws: 2,
      },
    ],
    enemyCamps: [
      {
        id: 'camp_bridge',
        tileX: 60,
        tileY: 20,
        aggroRadius: CAMP_AGGRO_DEFAULT + 1,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 140, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
            { type: 'enemy_archer', texture: 'unit-enemy-ranged', stats: ENEMY_ARCHER, count: 1 },
          ],
          maxActiveUnits: 8,
          patrolRadius: 8,
        },
      },
      {
        id: 'camp_enginarium',
        tileX: 40,
        tileY: 65,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 6, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
      },
      {
        id: 'camp_chapel',
        tileX: 70,
        tileY: 50,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
      },
      {
        id: 'camp_corridor_patrol',
        tileX: 30,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 30, y: 30 }, { x: 40, y: 30 }, { x: 40, y: 40 }, { x: 30, y: 40 },
        ],
      },
    ],
  },

  // ── Mission 5: Hold the Line (Survive intro) ──────────────────
  {
    id: 'hold_the_line',
    name: 'Hold the Line',
    description: 'Defend the forward listening post against ork assault waves. The position must not fall.',
    difficulty: 1,
    playerStartX: 40,
    playerStartY: 60,
    startingGold: 35,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    terrain: {
      waterCoverage: 0.04,
      stoneCoverage: 0.06,
      forestCoverage: 0.04,
      goldMineCount: 5,
      riverCount: 0,
    },
    objectives: [
      {
        id: 'obj_survive_outpost',
        type: 'survive',
        name: 'Defend the Outpost',
        description: 'Hold position at the listening post for 60 seconds.',
        tileX: 40,
        tileY: 30,
        surviveDurationMs: 60000,
        surviveRadius: 6,
        goldReward: 25,
        cardDraws: 3,
      },
      {
        id: 'obj_destroy_warcamp',
        type: 'destroy',
        name: 'Destroy Ork Warcamp',
        description: 'Raze the ork warcamp to the north to stop reinforcements.',
        tileX: 40,
        tileY: 10,
        targetCampId: 'camp_north_war',
        goldReward: 20,
        cardDraws: 2,
      },
    ],
    enemyCamps: [
      {
        id: 'camp_north_war',
        tileX: 40,
        tileY: 10,
        aggroRadius: CAMP_AGGRO_DEFAULT + 1,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 100, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
          ],
          maxActiveUnits: 8,
          patrolRadius: 10,
        },
      },
      {
        id: 'camp_east_flank',
        tileX: 65,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 65, y: 30 }, { x: 55, y: 30 }, { x: 55, y: 40 }, { x: 65, y: 40 },
        ],
      },
    ],
  },

  // ── Mission 6: Activate the Vox Array ─────────────────────────
  {
    id: 'vox_array',
    name: 'Activate the Vox Array',
    description: 'Reactivate two vox relay terminals to restore Imperial communications. Expect heavy resistance during activation.',
    difficulty: 2,
    playerStartX: 40,
    playerStartY: 70,
    startingGold: 25,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    extractionTimerMs: 45000,
    environmentModifiers: ['dense_fog'],
    terrain: {
      waterCoverage: 0.06,
      stoneCoverage: 0.04,
      forestCoverage: 0.10,
      goldMineCount: 6,
      riverCount: 1,
    },
    objectives: [
      {
        id: 'obj_activate_vox_west',
        type: 'activate',
        name: 'Activate Western Relay',
        description: 'Channel at the western vox terminal for 20 seconds.',
        tileX: 16,
        tileY: 30,
        channelDurationMs: 20000,
        goldReward: 20,
        cardDraws: 2,
      },
      {
        id: 'obj_activate_vox_east',
        type: 'activate',
        name: 'Activate Eastern Relay',
        description: 'Channel at the eastern vox terminal for 20 seconds.',
        tileX: 64,
        tileY: 30,
        channelDurationMs: 20000,
        goldReward: 20,
        cardDraws: 2,
      },
    ],
    optionalObjectives: [
      {
        id: 'obj_opt_purge_center',
        type: 'purge',
        name: 'Clear Central Garrison',
        description: 'Eliminate the ork patrol hub in the center.',
        tileX: 40,
        tileY: 30,
        purgeRadius: 6,
        goldReward: 15,
        cardDraws: 1,
      },
    ],
    enemyCamps: [
      {
        id: 'camp_west_vox',
        tileX: 16,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
      },
      {
        id: 'camp_east_vox',
        tileX: 64,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
      },
      {
        id: 'camp_center_patrol',
        tileX: 40,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 100, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 30000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
          ],
          maxActiveUnits: 6,
          patrolRadius: 12,
        },
      },
      {
        id: 'camp_fog_ambush',
        tileX: 40,
        tileY: 50,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 30, y: 50 }, { x: 50, y: 50 }, { x: 50, y: 60 }, { x: 30, y: 60 },
        ],
      },
    ],
  },

  // ── Mission 7: Scavenge and Evacuate ──────────────────────────
  {
    id: 'scavenge_evacuate',
    name: 'Scavenge and Evacuate',
    description: 'Recover scattered intel data-slates from the ruins before the ork horde arrives. No supply drops inbound.',
    difficulty: 2,
    playerStartX: 40,
    playerStartY: 70,
    startingGold: 30,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    extractionTimerMs: 40000,
    environmentModifiers: ['supply_shortage'],
    terrain: {
      waterCoverage: 0.03,
      stoneCoverage: 0.08,
      forestCoverage: 0.04,
      goldMineCount: 8,
      riverCount: 0,
    },
    objectives: [
      {
        id: 'obj_collect_intel',
        type: 'collect',
        name: 'Recover Intel Slates',
        description: 'Collect 4 data-slates from the ruins.',
        tileX: 40,
        tileY: 40,
        collectTotal: 4,
        collectPositions: [
          { tileX: 20, tileY: 20 },
          { tileX: 60, tileY: 20 },
          { tileX: 20, tileY: 55 },
          { tileX: 65, tileY: 50 },
        ],
        goldReward: 25,
        cardDraws: 2,
      },
    ],
    optionalObjectives: [
      {
        id: 'obj_opt_destroy_cache',
        type: 'destroy',
        name: 'Destroy Ammo Cache',
        description: 'Destroy the ork ammo dump to weaken their assault.',
        tileX: 40,
        tileY: 20,
        targetCampId: 'camp_center_ammo',
        goldReward: 20,
        cardDraws: 2,
      },
    ],
    pointsOfInterest: [
      { id: 'poi_gold1', type: 'gold_cache', tileX: 15, tileY: 40, reward: { gold: 10 } },
      { id: 'poi_gold2', type: 'gold_cache', tileX: 70, tileY: 35, reward: { gold: 10 } },
      { id: 'poi_ammo', type: 'ammo_dump', tileX: 35, tileY: 15, reward: { cardDraws: 1 } },
    ],
    enemyCamps: [
      {
        id: 'camp_center_ammo',
        tileX: 40,
        tileY: 20,
        aggroRadius: CAMP_AGGRO_DEFAULT + 1,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 120, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 30000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
          ],
          maxActiveUnits: 6,
          patrolRadius: 8,
        },
      },
      {
        id: 'camp_nw_ruins',
        tileX: 20,
        tileY: 20,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
      },
      {
        id: 'camp_ne_ruins',
        tileX: 60,
        tileY: 20,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 1, stats: ENEMY_ARCHER },
        ],
      },
      {
        id: 'camp_patrol_south',
        tileX: 50,
        tileY: 55,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 50, y: 55 }, { x: 65, y: 55 }, { x: 65, y: 45 }, { x: 50, y: 45 },
        ],
      },
    ],
  },

  // ── Mission 8: Armored Assault ────────────────────────────────
  {
    id: 'armored_assault',
    name: 'Armored Assault',
    description: 'Ork armor columns are entrenched across the valley. Destroy their fortifications and extract. Enemy units are heavily armored.',
    difficulty: 3,
    playerStartX: 40,
    playerStartY: 70,
    startingGold: 20,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    extractionTimerMs: 50000,
    environmentModifiers: ['armored_advance'],
    terrain: {
      waterCoverage: 0.05,
      stoneCoverage: 0.07,
      forestCoverage: 0.03,
      goldMineCount: 7,
      riverCount: 1,
    },
    objectives: [
      {
        id: 'obj_destroy_fort_w',
        type: 'destroy',
        name: 'Destroy Western Fort',
        description: 'Demolish the armored ork fortification.',
        tileX: 18,
        tileY: 30,
        targetCampId: 'camp_fort_west',
        goldReward: 25,
        cardDraws: 2,
      },
      {
        id: 'obj_destroy_fort_e',
        type: 'destroy',
        name: 'Destroy Eastern Fort',
        description: 'Demolish the armored ork fortification.',
        tileX: 62,
        tileY: 30,
        targetCampId: 'camp_fort_east',
        goldReward: 25,
        cardDraws: 2,
      },
      {
        id: 'obj_purge_hq',
        type: 'purge',
        name: 'Purge Command Post',
        description: 'Clear all hostiles from the central command area.',
        tileX: 40,
        tileY: 15,
        purgeRadius: 7,
        goldReward: 20,
        cardDraws: 2,
      },
    ],
    enemyCamps: [
      {
        id: 'camp_fort_west',
        tileX: 18,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT + 2,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 180, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
            { type: 'enemy_brute', texture: 'unit-enemy-brute', stats: ENEMY_BRUTE, count: 1 },
          ],
          maxActiveUnits: 8,
          patrolRadius: 8,
        },
      },
      {
        id: 'camp_fort_east',
        tileX: 62,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT + 2,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 180, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
            { type: 'enemy_brute', texture: 'unit-enemy-brute', stats: ENEMY_BRUTE, count: 1 },
          ],
          maxActiveUnits: 8,
          patrolRadius: 8,
        },
      },
      {
        id: 'camp_hq_center',
        tileX: 40,
        tileY: 15,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 6, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
        ],
      },
      {
        id: 'camp_roam_south',
        tileX: 40,
        tileY: 55,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 25, y: 55 }, { x: 55, y: 55 }, { x: 55, y: 45 }, { x: 25, y: 45 },
        ],
      },
    ],
  },

  // ── Mission 9: Night Raid ─────────────────────────────────────
  {
    id: 'night_raid',
    name: 'Night Raid',
    description: 'Under cover of darkness, activate the orbital beacon and recover the gene-seed cache. Reduced visibility, but your warriors strike harder.',
    difficulty: 2,
    playerStartX: 10,
    playerStartY: 40,
    startingGold: 25,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    extractionTimerMs: 35000,
    environmentModifiers: ['night_raid'],
    terrain: {
      waterCoverage: 0.04,
      stoneCoverage: 0.05,
      forestCoverage: 0.12,
      goldMineCount: 5,
      riverCount: 1,
    },
    objectives: [
      {
        id: 'obj_activate_beacon',
        type: 'activate',
        name: 'Activate Orbital Beacon',
        description: 'Channel at the beacon site for 25 seconds to signal the fleet.',
        tileX: 60,
        tileY: 20,
        channelDurationMs: 25000,
        goldReward: 25,
        cardDraws: 2,
      },
      {
        id: 'obj_recover_geneseed',
        type: 'recover',
        name: 'Recover Gene-Seed',
        description: 'Retrieve the fallen brother\'s gene-seed from the crash site.',
        tileX: 50,
        tileY: 60,
        goldReward: 20,
        cardDraws: 2,
      },
    ],
    optionalObjectives: [
      {
        id: 'obj_opt_destroy_lookout',
        type: 'destroy',
        name: 'Destroy Ork Lookout',
        description: 'Eliminate the ork watchtower before they raise the alarm.',
        tileX: 35,
        tileY: 30,
        targetCampId: 'camp_lookout',
        goldReward: 15,
        cardDraws: 1,
      },
    ],
    pointsOfInterest: [
      { id: 'poi_medkit', type: 'med_station', tileX: 30, tileY: 50, reward: { gold: 8 } },
      { id: 'poi_intel', type: 'intel', tileX: 70, tileY: 40, reward: { cardDraws: 1 } },
    ],
    enemyCamps: [
      {
        id: 'camp_beacon_guard',
        tileX: 60,
        tileY: 20,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
      },
      {
        id: 'camp_lookout',
        tileX: 35,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT + 2,
        units: [
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 2, stats: ENEMY_GRUNT },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 80, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 30000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
          ],
          maxActiveUnits: 6,
          patrolRadius: 10,
        },
      },
      {
        id: 'camp_crash_site',
        tileX: 50,
        tileY: 60,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
      },
      {
        id: 'camp_night_patrol',
        tileX: 40,
        tileY: 45,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 30, y: 45 }, { x: 50, y: 45 }, { x: 50, y: 35 }, { x: 30, y: 35 },
        ],
      },
    ],
  },

  // ── Mission 10: Green Tide ────────────────────────────────────
  {
    id: 'green_tide',
    name: 'Green Tide',
    description: 'WAAAGH! The greenskins are frenzied. Survive the ork assault, destroy their Mek Shop, and extract before you are overwhelmed.',
    difficulty: 3,
    playerStartX: 40,
    playerStartY: 70,
    startingGold: 25,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    extractionTimerMs: 50000,
    environmentModifiers: ['ork_frenzy'],
    terrain: {
      waterCoverage: 0.06,
      stoneCoverage: 0.03,
      forestCoverage: 0.05,
      goldMineCount: 7,
      riverCount: 1,
    },
    objectives: [
      {
        id: 'obj_survive_waaagh',
        type: 'survive',
        name: 'Survive the WAAAGH!',
        description: 'Hold your position against the ork assault for 90 seconds.',
        tileX: 40,
        tileY: 45,
        surviveDurationMs: 90000,
        surviveRadius: 7,
        goldReward: 30,
        cardDraws: 3,
      },
      {
        id: 'obj_destroy_mekshop',
        type: 'destroy',
        name: 'Destroy the Mek Shop',
        description: 'Demolish the ork Mek Shop producing war machines.',
        tileX: 40,
        tileY: 10,
        targetCampId: 'camp_mekshop',
        goldReward: 25,
        cardDraws: 2,
      },
    ],
    optionalObjectives: [
      {
        id: 'obj_opt_purge_flanks',
        type: 'purge',
        name: 'Purge Eastern Warband',
        description: 'Clear the eastern warband before they join the WAAAGH.',
        tileX: 68,
        tileY: 35,
        purgeRadius: 7,
        goldReward: 15,
        cardDraws: 1,
      },
    ],
    enemyCamps: [
      {
        id: 'camp_mekshop',
        tileX: 40,
        tileY: 10,
        aggroRadius: CAMP_AGGRO_DEFAULT + 2,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 6, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 200, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 18000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 3 },
            { type: 'enemy_archer', texture: 'unit-enemy-ranged', stats: ENEMY_ARCHER, count: 1 },
          ],
          maxActiveUnits: 12,
          patrolRadius: 15,
        },
      },
      {
        id: 'camp_east_warband',
        tileX: 68,
        tileY: 35,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
      },
      {
        id: 'camp_west_warband',
        tileX: 12,
        tileY: 35,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 12, y: 35 }, { x: 25, y: 35 }, { x: 25, y: 50 }, { x: 12, y: 50 },
        ],
      },
      {
        id: 'camp_mid_rush',
        tileX: 40,
        tileY: 30,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
      },
    ],
  },

  // ── Mission 11: Deep Strike (Space Hulk) ──────────────────────
  {
    id: 'deep_strike',
    name: 'Deep Strike',
    description: 'Breach the space hulk\'s inner sanctum. Activate the plasma reactors, collect navigation data, and extract through the fog.',
    difficulty: 3,
    playerStartX: 10,
    playerStartY: 40,
    startingGold: 20,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    extractionTimerMs: 50000,
    environmentModifiers: ['dense_fog'],
    terrain: {
      mapType: 'space_hulk',
      corridorWidth: 3,
      goldMineCount: 5,
    },
    objectives: [
      {
        id: 'obj_activate_reactor_a',
        type: 'activate',
        name: 'Activate Reactor Alpha',
        description: 'Channel at reactor Alpha for 20 seconds to restore power.',
        tileX: 35,
        tileY: 20,
        channelDurationMs: 20000,
        goldReward: 20,
        cardDraws: 2,
      },
      {
        id: 'obj_activate_reactor_b',
        type: 'activate',
        name: 'Activate Reactor Beta',
        description: 'Channel at reactor Beta for 20 seconds to restore power.',
        tileX: 55,
        tileY: 60,
        channelDurationMs: 20000,
        goldReward: 20,
        cardDraws: 2,
      },
      {
        id: 'obj_collect_navdata',
        type: 'collect',
        name: 'Recover Navigation Data',
        description: 'Collect 3 cogitator data-cores from the wreck.',
        tileX: 40,
        tileY: 40,
        collectTotal: 3,
        collectPositions: [
          { tileX: 25, tileY: 50 },
          { tileX: 60, tileY: 30 },
          { tileX: 45, tileY: 15 },
        ],
        goldReward: 20,
        cardDraws: 2,
      },
    ],
    optionalObjectives: [
      {
        id: 'obj_opt_recover_relic',
        type: 'recover',
        name: 'Recover Sacred Relic',
        description: 'Retrieve the Chapter relic from the shrine.',
        tileX: 70,
        tileY: 40,
        goldReward: 20,
        cardDraws: 2,
      },
    ],
    enemyCamps: [
      {
        id: 'camp_reactor_a',
        tileX: 35,
        tileY: 20,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 2, stats: ENEMY_ARCHER },
        ],
      },
      {
        id: 'camp_reactor_b',
        tileX: 55,
        tileY: 60,
        aggroRadius: CAMP_AGGRO_DEFAULT + 1,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 140, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 25000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
          ],
          maxActiveUnits: 6,
          patrolRadius: 8,
        },
      },
      {
        id: 'camp_corridor_ambush',
        tileX: 40,
        tileY: 40,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
        ],
      },
      {
        id: 'camp_shrine_guard',
        tileX: 70,
        tileY: 40,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
      },
      {
        id: 'camp_hulk_patrol',
        tileX: 20,
        tileY: 60,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 20, y: 60 }, { x: 20, y: 40 }, { x: 40, y: 40 }, { x: 40, y: 60 },
        ],
      },
    ],
  },

  // ── Mission 12: Exterminatus Omega (Helldive) ─────────────────
  {
    id: 'exterminatus_omega',
    name: 'Exterminatus Omega',
    description: 'Total purge. Destroy all ork strongholds, survive the counter-WAAAGH, and extract. The Emperor demands perfection.',
    difficulty: 4,
    playerStartX: 40,
    playerStartY: 74,
    startingGold: 15,
    supplyDropIntervalMs: SUPPLY_DROP_INTERVAL_MS,
    extractionTimerMs: 60000,
    environmentModifiers: ['ork_frenzy', 'armored_advance'],
    terrain: {
      waterCoverage: 0.08,
      stoneCoverage: 0.06,
      forestCoverage: 0.06,
      goldMineCount: 8,
      riverCount: 2,
    },
    objectives: [
      {
        id: 'obj_destroy_fortress_n',
        type: 'destroy',
        name: 'Destroy Northern Fortress',
        description: 'Raze the heavily fortified northern ork stronghold.',
        tileX: 40,
        tileY: 8,
        targetCampId: 'camp_fortress_north',
        goldReward: 30,
        cardDraws: 3,
      },
      {
        id: 'obj_destroy_fortress_w',
        type: 'destroy',
        name: 'Destroy Western Bastion',
        description: 'Demolish the western ork bastion.',
        tileX: 10,
        tileY: 35,
        targetCampId: 'camp_bastion_west',
        goldReward: 25,
        cardDraws: 2,
      },
      {
        id: 'obj_destroy_fortress_e',
        type: 'destroy',
        name: 'Destroy Eastern Bastion',
        description: 'Demolish the eastern ork bastion.',
        tileX: 70,
        tileY: 35,
        targetCampId: 'camp_bastion_east',
        goldReward: 25,
        cardDraws: 2,
      },
      {
        id: 'obj_survive_waaagh_omega',
        type: 'survive',
        name: 'Survive the Counter-WAAAGH',
        description: 'Hold your ground for 90 seconds against the ork counter-attack.',
        tileX: 40,
        tileY: 40,
        surviveDurationMs: 90000,
        surviveRadius: 8,
        goldReward: 30,
        cardDraws: 3,
      },
    ],
    optionalObjectives: [
      {
        id: 'obj_opt_collect_relics',
        type: 'collect',
        name: 'Recover Imperial Relics',
        description: 'Collect 3 sacred relics from the battlefield.',
        tileX: 40,
        tileY: 40,
        collectTotal: 3,
        collectPositions: [
          { tileX: 25, tileY: 15 },
          { tileX: 55, tileY: 55 },
          { tileX: 70, tileY: 15 },
        ],
        goldReward: 25,
        cardDraws: 2,
      },
    ],
    pointsOfInterest: [
      { id: 'poi_cache_sw', type: 'gold_cache', tileX: 15, tileY: 60, reward: { gold: 15 } },
      { id: 'poi_cache_se', type: 'gold_cache', tileX: 65, tileY: 60, reward: { gold: 15 } },
      { id: 'poi_ammo_mid', type: 'ammo_dump', tileX: 40, tileY: 25, reward: { cardDraws: 2 } },
    ],
    enemyCamps: [
      {
        id: 'camp_fortress_north',
        tileX: 40,
        tileY: 8,
        aggroRadius: CAMP_AGGRO_DEFAULT + 3,
        units: [
          { type: 'enemy_boss', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BOSS },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 3, stats: ENEMY_BRUTE },
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 4, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 300, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 18000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 3 },
            { type: 'enemy_archer', texture: 'unit-enemy-ranged', stats: ENEMY_ARCHER, count: 1 },
            { type: 'enemy_brute', texture: 'unit-enemy-brute', stats: ENEMY_BRUTE, count: 1 },
          ],
          maxActiveUnits: 14,
          patrolRadius: 15,
        },
      },
      {
        id: 'camp_bastion_west',
        tileX: 10,
        tileY: 35,
        aggroRadius: CAMP_AGGRO_DEFAULT + 2,
        units: [
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 200, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 22000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
            { type: 'enemy_archer', texture: 'unit-enemy-ranged', stats: ENEMY_ARCHER, count: 1 },
          ],
          maxActiveUnits: 10,
          patrolRadius: 10,
        },
      },
      {
        id: 'camp_bastion_east',
        tileX: 70,
        tileY: 35,
        aggroRadius: CAMP_AGGRO_DEFAULT + 2,
        units: [
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 2, stats: ENEMY_BRUTE },
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 5, stats: ENEMY_GRUNT },
          { type: 'enemy_archer', texture: 'unit-enemy-ranged', count: 3, stats: ENEMY_ARCHER },
        ],
        building: {
          texture: 'building-barracks',
          buildingType: 'enemy_outpost',
          stats: { maxHp: 200, tileWidth: 2, tileHeight: 2 },
        },
        spawner: {
          spawnInterval: 22000,
          spawnGroup: [
            { type: 'enemy_grunt', texture: 'unit-enemy', stats: ENEMY_GRUNT, count: 2 },
            { type: 'enemy_archer', texture: 'unit-enemy-ranged', stats: ENEMY_ARCHER, count: 1 },
          ],
          maxActiveUnits: 10,
          patrolRadius: 10,
        },
      },
      {
        id: 'camp_mid_garrison',
        tileX: 40,
        tileY: 40,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 4, stats: ENEMY_GRUNT },
          { type: 'enemy_brute', texture: 'unit-enemy-brute', count: 1, stats: ENEMY_BRUTE },
        ],
      },
      {
        id: 'camp_patrol_sw',
        tileX: 20,
        tileY: 55,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 20, y: 55 }, { x: 30, y: 55 }, { x: 30, y: 65 }, { x: 20, y: 65 },
        ],
      },
      {
        id: 'camp_patrol_se',
        tileX: 60,
        tileY: 55,
        aggroRadius: CAMP_AGGRO_DEFAULT,
        units: [
          { type: 'enemy_grunt', texture: 'unit-enemy', count: 3, stats: ENEMY_GRUNT },
        ],
        patrolPath: [
          { x: 60, y: 55 }, { x: 70, y: 55 }, { x: 70, y: 65 }, { x: 60, y: 65 },
        ],
      },
    ],
  },
];
