import { Card } from './Card';

export const CARD_DATABASE: Record<string, Card> = {
  // ── Adeptus Astartes Units ─────────────────────────────────────────
  servitor: {
    id: 'servitor',
    name: 'Servitor',
    type: 'unit',
    cost: 5,
    faction: 'neutral',
    description: 'Cyborg worker. Harvests requisition.',
    entityType: 'servitor',
    texture: 'unit-servitor',
  },
  guardsman: {
    id: 'guardsman',
    name: 'Guardsman',
    type: 'unit',
    cost: 15,
    faction: 'adeptus_astartes',
    description: 'Imperial Guard. Lasgun, 3 range, 5 dmg.',
    entityType: 'guardsman',
    texture: 'unit-guardsman',
  },
  marine: {
    id: 'marine',
    name: 'Space Marine',
    type: 'unit',
    cost: 12,
    faction: 'adeptus_astartes',
    description: 'Astartes. Chainsword, 10 dmg, heavy armor.',
    entityType: 'marine',
    texture: 'unit-marine',
  },
  scout: {
    id: 'scout',
    name: 'Scout Marine',
    type: 'unit',
    cost: 8,
    faction: 'adeptus_astartes',
    description: 'Fast recon. Light armor, combat knife.',
    entityType: 'scout',
    texture: 'unit-scout',
  },
  ogryn: {
    id: 'ogryn',
    name: 'Ogryn',
    type: 'unit',
    cost: 20,
    faction: 'neutral',
    description: 'Abhuman brute. 120 HP, 15 dmg, very slow.',
    entityType: 'ogryn',
    texture: 'unit-ogryn',
  },
  techmarine: {
    id: 'techmarine',
    name: 'Techmarine',
    type: 'unit',
    cost: 14,
    faction: 'adeptus_astartes',
    description: 'Adeptus Mechanicus. Servo-arm melee, repairs nearby buildings.',
    entityType: 'techmarine',
    texture: 'unit-techmarine',
  },
  rhino: {
    id: 'rhino',
    name: 'Rhino APC',
    type: 'unit',
    cost: 25,
    faction: 'adeptus_astartes',
    description: 'Armored transport. Fast, tough, storm bolter.',
    entityType: 'rhino',
    texture: 'unit-rhino',
  },
  leman_russ: {
    id: 'leman_russ',
    name: 'Leman Russ',
    type: 'unit',
    cost: 40,
    faction: 'adeptus_astartes',
    description: 'Battle tank. Battle cannon, 5 range, 25 dmg, heavy armor.',
    entityType: 'leman_russ',
    texture: 'unit-leman_russ',
  },
  sentinel: {
    id: 'sentinel',
    name: 'Sentinel',
    type: 'unit',
    cost: 18,
    faction: 'adeptus_astartes',
    description: 'Scout walker. Multilaser, 4 range, fast recon.',
    entityType: 'sentinel',
    texture: 'unit-sentinel',
  },

  // ── Buildings ──────────────────────────────────────────────────────
  tarantula: {
    id: 'tarantula',
    name: 'Tarantula Turret',
    type: 'building',
    cost: 20,
    faction: 'adeptus_astartes',
    description: 'Auto-targets xenos, 4 range, 8 dmg.',
    entityType: 'tarantula',
    texture: 'building-tarantula',
    tileWidth: 1,
    tileHeight: 1,
  },
  aegis: {
    id: 'aegis',
    name: 'Aegis Defence Line',
    type: 'building',
    cost: 8,
    faction: 'neutral',
    description: 'Fortified barricade, 150 HP, 5 armor.',
    entityType: 'aegis',
    texture: 'building-aegis',
    tileWidth: 1,
    tileHeight: 1,
  },
  barracks: {
    id: 'barracks',
    name: 'Barracks',
    type: 'building',
    cost: 30,
    faction: 'adeptus_astartes',
    description: '+2 ATK aura (r4), +1 card per incursion.',
    entityType: 'barracks',
    texture: 'building-barracks',
    tileWidth: 2,
    tileHeight: 2,
  },
  sanctum: {
    id: 'sanctum',
    name: 'Sanctum Imperialis',
    type: 'building',
    cost: 18,
    faction: 'adeptus_astartes',
    description: 'Shrine-medica. Heals nearby units 1 HP/s (r3).',
    entityType: 'sanctum',
    texture: 'building-sanctum',
    tileWidth: 1,
    tileHeight: 1,
  },

  // ── Ordnance ───────────────────────────────────────────────────────
  narthecium: {
    id: 'narthecium',
    name: 'Apothecary Aid',
    type: 'ordnance',
    cost: 10,
    faction: 'adeptus_astartes',
    description: 'Narthecium field heal, 20 HP in radius.',
    ordnanceEffect: 'narthecium',
    ordnanceRadius: 5,
    ordnanceValue: 20,
  },
  lance_strike: {
    id: 'lance_strike',
    name: 'Lance Strike',
    type: 'ordnance',
    cost: 15,
    faction: 'neutral',
    description: 'Lance bombardment. 30 AoE damage. Single use.',
    ordnanceEffect: 'lance_strike',
    ordnanceRadius: 3,
    ordnanceValue: 30,
    singleUse: true,
  },
  frag_storm: {
    id: 'frag_storm',
    name: 'Frag Storm',
    type: 'ordnance',
    cost: 10,
    faction: 'neutral',
    description: 'Fragmentation barrage. 15 dmg, wide radius. Single use.',
    ordnanceEffect: 'lance_strike',
    ordnanceRadius: 5,
    ordnanceValue: 15,
    singleUse: true,
  },
  melta_strike: {
    id: 'melta_strike',
    name: 'Melta Strike',
    type: 'ordnance',
    cost: 20,
    faction: 'neutral',
    description: 'Focused melta beam. 50 dmg, pinpoint. Single use.',
    ordnanceEffect: 'lance_strike',
    ordnanceRadius: 1,
    ordnanceValue: 50,
    singleUse: true,
  },
  stasis_bomb: {
    id: 'stasis_bomb',
    name: 'Stasis Bomb',
    type: 'ordnance',
    cost: 12,
    faction: 'neutral',
    description: 'Chrono charge. Freezes xenos in radius for 4s. Single use.',
    ordnanceEffect: 'stasis',
    ordnanceRadius: 3,
    ordnanceValue: 4000,
    singleUse: true,
  },
  vortex_charge: {
    id: 'vortex_charge',
    name: 'Vortex Charge',
    type: 'ordnance',
    cost: 25,
    faction: 'neutral',
    description: 'Warp vortex. 40 dmg, pulls xenos toward center. Single use.',
    ordnanceEffect: 'vortex',
    ordnanceRadius: 4,
    ordnanceValue: 40,
    singleUse: true,
  },
  blessed_armour: {
    id: 'blessed_armour',
    name: 'Blessed Armour',
    type: 'ordnance',
    cost: 12,
    faction: 'adeptus_astartes',
    description: 'Techpriest blessing. +5 max HP, full heal.',
    ordnanceEffect: 'blessed_armour',
    ordnanceRadius: 0,
    ordnanceValue: 5,
  },
  krak_missile: {
    id: 'krak_missile',
    name: 'Krak Missile',
    type: 'ordnance',
    cost: 8,
    faction: 'neutral',
    description: 'Anti-armor missile. 25 dmg, pinpoint. Single use.',
    ordnanceEffect: 'lance_strike',
    ordnanceRadius: 1,
    ordnanceValue: 25,
    singleUse: true,
  },
  rally_order: {
    id: 'rally_order',
    name: 'Rally Order',
    type: 'ordnance',
    cost: 10,
    faction: 'neutral',
    description: 'Vox broadcast. +50% speed to allies in radius for 5s.',
    ordnanceEffect: 'rally',
    ordnanceRadius: 4,
    ordnanceValue: 5000,
  },
  smoke_barrage: {
    id: 'smoke_barrage',
    name: 'Smoke Barrage',
    type: 'ordnance',
    cost: 10,
    faction: 'neutral',
    description: 'Obscuring smoke. Enemies in radius slowed and attack 3x slower for 5s. Single use.',
    ordnanceEffect: 'smoke',
    ordnanceRadius: 3,
    ordnanceValue: 5000,
    singleUse: true,
  },

  // ── Doctrines ──────────────────────────────────────────────────────

  // Economy Doctrines
  logis_protocol: {
    id: 'logis_protocol',
    name: 'Logis Protocol',
    type: 'doctrine',
    cost: 20,
    faction: 'neutral',
    description: 'Adeptus Mechanicus efficiency. Servitors harvest 50% faster.',
    doctrineEffect: 'gather_speed',
    doctrineFilter: 'servitor',
    doctrineValue: 1.5,
  },
  tithe_collector: {
    id: 'tithe_collector',
    name: 'Tithe Collector',
    type: 'doctrine',
    cost: 15,
    faction: 'neutral',
    description: 'Imperial tithe. +1g per card played.',
    doctrineEffect: 'tithe_collector',
    doctrineValue: 1,
  },
  scavenger_rites: {
    id: 'scavenger_rites',
    name: 'Scavenger Rites',
    type: 'doctrine',
    cost: 15,
    faction: 'neutral',
    description: 'Battlefield salvage. +1g per enemy killed.',
    doctrineEffect: 'scavenger_rites',
    doctrineValue: 1,
  },
  forward_supply: {
    id: 'forward_supply',
    name: 'Forward Supply',
    type: 'doctrine',
    cost: 20,
    faction: 'neutral',
    description: 'Logistics chain. Supply drops arrive 30% sooner.',
    doctrineEffect: 'forward_supply',
    doctrineValue: 0.7,
  },
  war_spoils: {
    id: 'war_spoils',
    name: 'War Spoils',
    type: 'doctrine',
    cost: 25,
    faction: 'neutral',
    description: 'Plunder directive. Objective gold rewards +25%.',
    doctrineEffect: 'war_spoils',
    doctrineValue: 1.25,
  },

  // Combat Doctrines
  blessed_bolts: {
    id: 'blessed_bolts',
    name: 'Blessed Bolts',
    type: 'doctrine',
    cost: 25,
    faction: 'adeptus_astartes',
    description: 'Consecrated ammo. All Guardsmen +3 dmg.',
    doctrineEffect: 'damage_boost',
    doctrineFilter: 'guardsman',
    doctrineValue: 3,
  },
  gene_seed: {
    id: 'gene_seed',
    name: 'Gene Seed',
    type: 'doctrine',
    cost: 30,
    faction: 'adeptus_astartes',
    description: 'Geneseed recovery. Marines that die have 25% chance to respawn at drop ship.',
    doctrineEffect: 'gene_seed',
    doctrineValue: 0.25,
  },
  overwatch_protocol: {
    id: 'overwatch_protocol',
    name: 'Overwatch Protocol',
    type: 'doctrine',
    cost: 20,
    faction: 'neutral',
    description: 'Fire control. Buildings attack 25% faster.',
    doctrineEffect: 'overwatch_protocol',
    doctrineValue: 0.75,
  },
  fury_of_emperor: {
    id: 'fury_of_emperor',
    name: 'Fury of the Emperor',
    type: 'doctrine',
    cost: 25,
    faction: 'adeptus_astartes',
    description: 'Holy wrath. All melee units +20% attack speed.',
    doctrineEffect: 'attack_speed',
    doctrineFilter: 'melee',
    doctrineValue: 0.2,
  },
  suppressing_fire: {
    id: 'suppressing_fire',
    name: 'Suppressing Fire',
    type: 'doctrine',
    cost: 20,
    faction: 'neutral',
    description: 'Covering fire. Ranged units have 15% chance to slow target.',
    doctrineEffect: 'suppressing_fire',
    doctrineValue: 0.15,
  },

  // Defensive Doctrines
  fortification_doctrine: {
    id: 'fortification_doctrine',
    name: 'Fortification Doctrine',
    type: 'doctrine',
    cost: 15,
    faction: 'neutral',
    description: 'Imperial engineering. Buildings +30% HP.',
    doctrineEffect: 'fortification',
    doctrineValue: 1.3,
  },
  shield_of_faith: {
    id: 'shield_of_faith',
    name: 'Shield of Faith',
    type: 'doctrine',
    cost: 20,
    faction: 'adeptus_astartes',
    description: 'Emperor\'s protection. All units +1 armor.',
    doctrineEffect: 'armor_boost',
    doctrineValue: 1,
  },
  apothecary_protocols: {
    id: 'apothecary_protocols',
    name: 'Apothecary Protocols',
    type: 'doctrine',
    cost: 25,
    faction: 'adeptus_astartes',
    description: 'Field medicine. Units heal 1 HP/5s when not in combat.',
    doctrineEffect: 'apothecary_protocols',
    doctrineValue: 1,
  },
  fall_back: {
    id: 'fall_back',
    name: 'Fall Back!',
    type: 'doctrine',
    cost: 20,
    faction: 'neutral',
    description: 'Tactical retreat. Units below 25% HP get +30% move speed.',
    doctrineEffect: 'fall_back',
    doctrineValue: 1.3,
  },

  // Tactical Doctrines
  vanguard_deployment: {
    id: 'vanguard_deployment',
    name: 'Vanguard Deployment',
    type: 'doctrine',
    cost: 20,
    faction: 'adeptus_astartes',
    description: 'Forward strike. First unit played each objective costs 0g.',
    doctrineEffect: 'vanguard_deployment',
    doctrineValue: 1,
  },
  requisition_officer: {
    id: 'requisition_officer',
    name: 'Requisition Officer',
    type: 'doctrine',
    cost: 25,
    faction: 'neutral',
    description: 'Expanded command. +1 hand size (6 cards).',
    doctrineEffect: 'requisition_officer',
    doctrineValue: 1,
  },
  combat_resupply: {
    id: 'combat_resupply',
    name: 'Combat Resupply',
    type: 'doctrine',
    cost: 20,
    faction: 'neutral',
    description: 'Field logistics. +1 discard per objective.',
    doctrineEffect: 'combat_resupply',
    doctrineValue: 1,
  },
  auspex_sweep: {
    id: 'auspex_sweep',
    name: 'Auspex Sweep',
    type: 'doctrine',
    cost: 15,
    faction: 'adeptus_astartes',
    description: 'Sensor sweep. All units +2 sight radius.',
    doctrineEffect: 'auspex_sweep',
    doctrineValue: 2,
  },
  drop_pod_assault: {
    id: 'drop_pod_assault',
    name: 'Drop Pod Assault',
    type: 'doctrine',
    cost: 30,
    faction: 'adeptus_astartes',
    description: 'Orbital insertion. Units deploy with 3s invulnerability.',
    doctrineEffect: 'drop_pod_assault',
    doctrineValue: 3000,
  },
  combined_arms: {
    id: 'combined_arms',
    name: 'Combined Arms',
    type: 'doctrine',
    cost: 25,
    faction: 'neutral',
    description: 'Coordinated assault. Ranged + melee near each other both get +2 dmg.',
    doctrineEffect: 'combined_arms',
    doctrineValue: 2,
  },

  // ── Equipment / Wargear Cards ──────────────────────────────────────
  heated_bolts: {
    id: 'heated_bolts',
    name: 'Heated Bolts',
    type: 'equipment',
    cost: 15,
    faction: 'adeptus_astartes',
    description: 'Incendiary rounds. Equip Guardsman: +4 dmg.',
    equipEffect: 'damage_boost',
    equipFilter: 'guardsman',
    equipValue: 4,
    wargear: {
      statBoosts: [{ stat: 'damage', value: 4, mode: 'additive' }],
    },
  },
  ceramite_plating: {
    id: 'ceramite_plating',
    name: 'Ceramite Plating',
    type: 'equipment',
    cost: 12,
    faction: 'neutral',
    description: 'Extra armor. Equip any unit: +15 HP.',
    equipEffect: 'hp_boost',
    equipValue: 15,
    wargear: {
      statBoosts: [{ stat: 'hp', value: 15, mode: 'additive' }],
    },
  },
  stim_injector: {
    id: 'stim_injector',
    name: 'Stim Injector',
    type: 'equipment',
    cost: 10,
    faction: 'neutral',
    description: 'Combat stim. Equip any unit: +30% speed.',
    equipEffect: 'speed_boost',
    equipValue: 1.3,
    wargear: {
      statBoosts: [{ stat: 'speed', value: 1.3, mode: 'multiplicative' }],
    },
  },
  power_fist: {
    id: 'power_fist',
    name: 'Power Fist',
    type: 'equipment',
    cost: 18,
    faction: 'adeptus_astartes',
    description: 'Ceramite gauntlet. Marine only: +6 dmg, stun on hit.',
    equipFilter: 'marine',
    wargear: {
      statBoosts: [{ stat: 'damage', value: 6, mode: 'additive' }],
      passives: [{ id: 'stun_on_hit', params: { duration: 500 } }],
    },
  },
  jump_pack: {
    id: 'jump_pack',
    name: 'Jump Pack',
    type: 'equipment',
    cost: 20,
    faction: 'adeptus_astartes',
    description: 'Assault jump pack. Marine/Scout: Leap 4 tiles + AoE.',
    equipFilter: 'marine,scout',
    wargear: {
      ability: {
        id: 'jump_pack_leap',
        name: 'Leap',
        hotkey: 'E',
        cooldown: 20000,
        color: 0x4488ff,
        params: { distance: 4, damage: 10, radius: 1 },
      },
    },
  },
  storm_shield: {
    id: 'storm_shield',
    name: 'Storm Shield',
    type: 'equipment',
    cost: 16,
    faction: 'adeptus_astartes',
    description: 'Refractor field. Marine only: +5 armor, 25% block.',
    equipFilter: 'marine',
    wargear: {
      statBoosts: [{ stat: 'armor', value: 5, mode: 'additive' }],
      passives: [{ id: 'block_chance', params: { chance: 0.25 } }],
    },
  },
  auspex: {
    id: 'auspex',
    name: 'Auspex',
    type: 'equipment',
    cost: 14,
    faction: 'adeptus_astartes',
    description: 'Sensor array. Any unit: +3 vision, -2 enemy armor aura.',
    wargear: {
      statBoosts: [{ stat: 'vision', value: 3, mode: 'additive' }],
      passives: [{ id: 'armor_debuff_aura', params: { value: 2, radius: 3 } }],
    },
  },
  frag_grenades: {
    id: 'frag_grenades',
    name: 'Frag Grenades',
    type: 'equipment',
    cost: 12,
    faction: 'neutral',
    description: 'Fragmentation charges. Guardsman/Scout: throw AoE.',
    equipFilter: 'guardsman,scout',
    wargear: {
      ability: {
        id: 'frag_grenade_throw',
        name: 'Throw',
        hotkey: 'E',
        cooldown: 12000,
        color: 0xff6600,
        params: { damage: 15, radius: 2, range: 3 },
      },
    },
  },
  reductor: {
    id: 'reductor',
    name: 'Reductor',
    type: 'equipment',
    cost: 15,
    faction: 'neutral',
    description: 'Medicae tool. Servitor only: heal ally 20 HP.',
    equipFilter: 'servitor',
    wargear: {
      ability: {
        id: 'reductor_heal',
        name: 'Heal',
        hotkey: 'E',
        cooldown: 15000,
        color: 0x44ff88,
        params: { amount: 20, range: 2 },
      },
    },
  },
  iron_halo: {
    id: 'iron_halo',
    name: 'Iron Halo',
    type: 'equipment',
    cost: 18,
    faction: 'adeptus_astartes',
    description: 'Rosarius field. Any unit: +10 HP, absorb first hit (30s).',
    wargear: {
      statBoosts: [{ stat: 'hp', value: 10, mode: 'additive' }],
      passives: [{ id: 'damage_shield', params: { recharge: 30000 } }],
    },
  },
  camo_cloak: {
    id: 'camo_cloak',
    name: 'Camo Cloak',
    type: 'equipment',
    cost: 10,
    faction: 'adeptus_astartes',
    description: 'Stealth mantle. Scout only: +3 vision, +40% speed.',
    equipFilter: 'scout',
    wargear: {
      statBoosts: [
        { stat: 'vision', value: 3, mode: 'additive' },
        { stat: 'speed', value: 1.4, mode: 'multiplicative' },
      ],
    },
  },
  melta_bomb: {
    id: 'melta_bomb',
    name: 'Melta Bomb',
    type: 'equipment',
    cost: 14,
    faction: 'neutral',
    description: 'Anti-structure charge. Any unit: plant bomb for 40 dmg.',
    wargear: {
      ability: {
        id: 'melta_bomb_plant',
        name: 'Plant Bomb',
        hotkey: 'E',
        cooldown: 25000,
        color: 0xff4400,
        params: { damage: 40, radius: 1, range: 1 },
      },
    },
  },
  servo_skull: {
    id: 'servo_skull',
    name: 'Servo-Skull',
    type: 'equipment',
    cost: 8,
    faction: 'neutral',
    description: 'Floating drone. Any unit: +4 vision, +1 range.',
    wargear: {
      statBoosts: [
        { stat: 'vision', value: 4, mode: 'additive' },
        { stat: 'range', value: 1, mode: 'additive' },
      ],
    },
  },
};

export function getCard(id: string): Card | undefined {
  return CARD_DATABASE[id];
}

export function getAllCards(): Card[] {
  return Object.values(CARD_DATABASE);
}

export function getCardsByType(type: Card['type']): Card[] {
  return getAllCards().filter((c) => c.type === type);
}

export function getCardsByFaction(faction: Card['faction']): Card[] {
  return getAllCards().filter((c) => c.faction === faction || c.faction === 'neutral');
}
